run:
  timeout: 10m

linters:
  enable:
    - misspell
    - godot
    - goheader

linters-settings:
  misspell:
    locale: US
  godox:
    keywords:
      - FIXME
  goheader:
    template: |-
      Copyright 2015 Tim Heckman. All rights reserved.
      Copyright 2018-{{ YEAR }} The Gofrs. All rights reserved.
      Use of this source code is governed by the BSD 3-Clause
      license that can be found in the LICENSE file.

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  show-stats: true
  sort-results: true
  sort-order:
    - linter
    - file
